[pytest]
testpaths = test
python_files = *test*.py
python_classes = *Test*
python_functions = *test*

markers = ui : тесты UI
          api : тесты API
          positive : позитивный тест
          negative : негативный тест
